### ISSUE TITLE
Missing license information

### ISSUE THREAD

**Issue by jmewes** [sadatrafsanjani/JavaFX-Point-of-Sales#1]
Please add a license information if you want to allow other people building on top of your work.

**Comment by jmewes** [comment]
What I have in mind is building a prototype for an open-source JavaFX application which uses [OpenMRS](http://openmrs.org/) as backend via its REST API.

The application you have demonstrated [in this video](https://www.youtube.com/watch?v=FraDbuVU1Qs) is kind of what I have in mind so it would be nice if we could be allowed reuse this.

**Comment by jmewes** [comment]
Thank you!

**Comment by sadatrafsanjani** [comment]
please support my work and follow me.

**Comment by jmewes** [comment]
If you react on the pull requests I could also support your work by sending some of the improvements I am doing in my fork back to you.

https://github.com/sadatrafsanjani/JavaFX-Point-of-Sales/pulls
