### ISSUE TITLE
Database not starting 

### ISSUE THREAD

**Issue by dirm02** [sadatrafsanjani/JavaFX-Point-of-Sales#4]
Hey i have an issue starting the application ; it keeps telling me databse connection error ; I am pretty sure everything is in place ; inventory.sql is in my projects ; I even started to compile the queries in mysql db IDE ;Please help 
![error](https://user-images.githubusercontent.com/16779064/39503057-46acbcee-4d89-11e8-9d92-77177ba0934c.PNG)

**Comment by sadatrafsanjani** [comment]
ok,

use mysql database and export the sql file in the mysql database
called inventory. To avoid further problem, please use netbean IDE or
the stand alone jar file to start up the project.
Which are are you from?

On 5/2/18, dirm02 <notifications@github.com> wrote:
> Hey i have an issue starting the application ; it keeps telling me databse
> connection error ; I am pretty sure everything is in place ; inventory.sql
> is in my projects ; I even started to compile the queries in mysql db IDE
> ;Please help
> ![error](https://user-images.githubusercontent.com/16779064/39503057-46acbcee-4d89-11e8-9d92-77177ba0934c.PNG)
>
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/sadatrafsanjani/JavaFX-Point-of-Sales/issues/4


-- 
Mohammad Sadat Hussain Rafsanjani
www.sadatrafsanjani.com
01705571619

**Comment by dirm02** [comment]
Look I did what you asked and still the same issue Please help  : 
![image](https://user-images.githubusercontent.com/16779064/39588520-880f39f8-4ec1-11e8-9bff-7e8365a33390.png)
![image](https://user-images.githubusercontent.com/16779064/39588562-a0738a6c-4ec1-11e8-9cfd-c9ce7c09d2af.png)
![image](https://user-images.githubusercontent.com/16779064/39588583-ab83a1d0-4ec1-11e8-8535-364ff553eff7.png)

**Comment by dirm02** [comment]
And When I open up in Netbeans . It gives me a lot of error before i compile the project; LOOK
![image](https://user-images.githubusercontent.com/16779064/39596945-8d3eb7b0-4ed9-11e8-8e2d-d52b4337d166.png)

**Comment by dirm02** [comment]
Look when I start the project in netbeans ; it says the same problem; even when I start the program from the stand alone executable jar <inventory.jar>LOOK:
![image](https://user-images.githubusercontent.com/16779064/39597448-0d37b678-4edb-11e8-980f-d8c2bac4f3db.png)

**Comment by dirm02** [comment]
Same error when I start inventory with mysql IDE and netbeans IDE ; Please help ; just tell me step by step how to lunch this projects : Look 
![image](https://user-images.githubusercontent.com/16779064/39605502-6ab3e6a8-4ef6-11e8-932f-9e69f41b5db0.png)

**Comment by sadatrafsanjani** [comment]
after opening the project in netbeas (8.2) right click on the project
and build with dependencies. Then start mysql server, check port
numbers, username, password properly. The system is well tested and
working properly across a lot of pc.

On 5/4/18, dirm02 <notifications@github.com> wrote:
> Same error when I start inventory with mysql IDE and netbeans IDE ; Please
> help ; just tell me step by step how to lunch this projects : Look
> ![image](https://user-images.githubusercontent.com/16779064/39605502-6ab3e6a8-4ef6-11e8-932f-9e69f41b5db0.png)
>
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/sadatrafsanjani/JavaFX-Point-of-Sales/issues/4#issuecomment-386454691


-- 
Mohammad Sadat Hussain Rafsanjani
www.sadatrafsanjani.com
01705571619

**Comment by dirm02** [comment]
Please where can I check < check port numbers, username, password>?? which file in your project ; because mysql server is running and it says the same issue; Actually what is the password you have set it up so that I try with that and the username

**Comment by sadatrafsanjani** [comment]
in your mysql database, username should be root, password must be
blank and mysql default port should be 3306

On 5/5/18, dirm02 <notifications@github.com> wrote:
> bro where can I check < check port numbers, username, password>?? which file
> in your project ; because mysql server is running and it says the same
> issue;
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/sadatrafsanjani/JavaFX-Point-of-Sales/issues/4#issuecomment-386794937


-- 
Mohammad Sadat Hussain Rafsanjani
www.sadatrafsanjani.com
01705571619

**Comment by dirm02** [comment]
Right ; Is there any other way I can match my username and password on mysql database ? I mean going into a class in the project and write username is this and password is that ?! I wonder ; otherwise i will do root and blank ; 
It is just that I have to reinstall mysql server to change the password and username ;

**Comment by sadatrafsanjani** [comment]
Sure, there is a way. Go to the hibernate.cfg inside
source/main/resources folder and change username and password using
these two lines
<property name="hibernate.connection.username">username</property>
<property name="hibernate.connection.password">password</property>

On 5/5/18, dirm02 <notifications@github.com> wrote:
> Right ; Is there any other way I can match my username and password on mysql
> database ? I mean going into a class in the project and write usernmae is
> this and password is that ?! I wonder ; otherwise i will do root and blank ;
>
> It is just that I have to reinstall mysql server to change the password and
> username ;
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/sadatrafsanjani/JavaFX-Point-of-Sales/issues/4#issuecomment-386797704


-- 
Mohammad Sadat Hussain Rafsanjani
www.sadatrafsanjani.com
01705571619

**Comment by dirm02** [comment]
That is what I thought ; I have seen this file . i only notice the username and wondered where could the password property be ?! I actually added the property password field ; but it says database connection error again !! which mean it is not coming from the code but the mysql server ; 
So tell what software are you using ? me I have mysql workbench and when i start this , the server automatically starts ; Please guide me again , i am so sorry to bother you this much

**Comment by dirm02** [comment]
Can you use Teamviewer so that you can fix my project Please ; It is best solution I can come up with sir . I will be connected until you come online

**Comment by dirm02** [comment]
I swear I used xampp too , lunched mysql server at localhost ; fix the username and password and nothing changed ; same error ; Please come online fast

**Comment by sadatrafsanjani** [comment]
use xampp server and with username root and password empty

On 5/6/18, dirm02 <notifications@github.com> wrote:
> I swear I used xampp too , lunched mysql server at localhost ; fix the
> username and password and nothing changed ; same error ; Please come online
> fast
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/sadatrafsanjani/JavaFX-Point-of-Sales/issues/4#issuecomment-386843791


-- 
Mohammad Sadat Hussain Rafsanjani
www.sadatrafsanjani.com
01705571619

**Comment by dirm02** [comment]
I am using xampp ; imported the database ; I can see the test database is all the tables from inventory; then lunched the code and I get the same error ; that is why i need you to come online on teamviewer please;
