### ISSUE TITLE
Unable to Run with Netbeans

### ISSUE THREAD

**Issue by Rahumathulla** [sadatrafsanjani/JavaFX-Point-of-Sales#5]
--- exec-maven-plugin:1.2.1:exec (unpack-dependencies) @ inventory ---
------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time: 1:32.640s
Finished at: Sun May 06 00:29:57 IST 2018
Final Memory: 14M/210M
------------------------------------------------------------------------
Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (unpack-dependencies) on project inventory: Command execution failed. Cannot run program "C:\Program Files\Java\jdk1.8.0_20\jre\bin\javafxpackager" (in directory "C:\Users\rahumathulla\Documents\NetBeansProjects\trunk"): CreateProcess error=2, The system cannot find the file specified -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by sadatrafsanjani** [comment]
use neatbeans 8.2 and upon opening the project try build with dependency

On 5/6/18, Rahumathulla <notifications@github.com> wrote:
> --- exec-maven-plugin:1.2.1:exec (unpack-dependencies) @ inventory ---
> ------------------------------------------------------------------------
> BUILD FAILURE
> ------------------------------------------------------------------------
> Total time: 1:32.640s
> Finished at: Sun May 06 00:29:57 IST 2018
> Final Memory: 14M/210M
> ------------------------------------------------------------------------
> Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec
> (unpack-dependencies) on project inventory: Command execution failed. Cannot
> run program "C:\Program Files\Java\jdk1.8.0_20\jre\bin\javafxpackager" (in
> directory "C:\Users\rahumathulla\Documents\NetBeansProjects\trunk"):
> CreateProcess error=2, The system cannot find the file specified -> [Help
> 1]
>
> To see the full stack trace of the errors, re-run Maven with the -e switch.
> Re-run Maven using the -X switch to enable full debug logging.
>
> For more information about the errors and possible solutions, please read
> the following articles:
> [Help 1]
> http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/sadatrafsanjani/JavaFX-Point-of-Sales/issues/5


-- 
Mohammad Sadat Hussain Rafsanjani
www.sadatrafsanjani.com
01705571619

**Comment by infobalu** [comment]
<dependency>
	<groupId>org.controlsfx</groupId>
	<artifactId>openjfx-dialogs</artifactId>
	<version>1.0.3</version>
</dependency>

**Comment by infobalu** [comment]
<dependency>
	<groupId>org.controlsfx</groupId>
	<artifactId>openjfx-dialogs</artifactId>
	<version>1.0.3</version>
</dependency>

**Comment by sadatrafsanjani** [comment]
this system runs on java 8. probably you are using later versions
which lacks javafx sdk.

On 2/4/20, infobalu <notifications@github.com> wrote:
>  <dependency>
> 	<groupId>org.controlsfx</groupId>
> 	<artifactId>openjfx-dialogs</artifactId>
> 	<version>1.0.3</version>
> </dependency>
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/sadatrafsanjani/JavaFX-Point-of-Sales/issues/5#issuecomment-581779172


-- 
Regards,

Mohammad Sadat Hussain Rafsanjani
Software Engineer
ServicEngine
Cell: (+880) 170 557 1619
GitHub: sadatrafsanjani
