### ISSUE TITLE
Database Connection Error

### ISSUE THREAD

**Issue by AirtonB** [sadatrafsanjani/JavaFX-Point-of-Sales#6]
when the project runs show this error below:

--- exec-maven-plugin:1.2.1:exec (default-cli) @ inventory ---
jul 26, 2018 9:00:00 AM org.hibernate.Version logVersion
INFO: HHH000412: Hibernate Core {5.1.0.Final}
jul 26, 2018 9:00:00 AM org.hibernate.cfg.Environment <clinit>
INFO: HHH000206: hibernate.properties not found
jul 26, 2018 9:00:00 AM org.hibernate.cfg.Environment buildBytecodeProvider
INFO: HHH000021: Bytecode provider name : javassist
jul 26, 2018 9:00:01 AM org.hibernate.annotations.common.reflection.java.JavaReflectionManager <clinit>
INFO: HCANN000001: Hibernate Commons Annotations {5.0.1.Final}
jul 26, 2018 9:00:01 AM org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl configure
WARN: HHH10001002: Using Hibernate built-in connection pool (not for production use!)
jul 26, 2018 9:00:01 AM org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl buildCreator
INFO: HHH10001005: using driver [com.mysql.jdbc.Driver] at URL [jdbc:mysql://localhost:3306/inventory]
jul 26, 2018 9:00:01 AM org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl buildCreator
INFO: HHH10001001: Connection properties: {user=root}
jul 26, 2018 9:00:01 AM org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl buildCreator
INFO: HHH10001003: Autocommit mode: false
jul 26, 2018 9:00:01 AM org.hibernate.engine.jdbc.connections.internal.PooledConnections <init>
INFO: HHH000115: Hibernate connection pool size: 20 (min=1)
jul 26, 2018 9:00:03 AM org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl stop
INFO: HHH10001008: Cleaning up connection pool [jdbc:mysql://localhost:3306/inventory]
------------------------------------------------------------------------
BUILD SUCCESS
------------------------------------------------------------------------
Total time: 3:13.659s
Finished at: Thu Jul 26 09:01:09 BRT 2018
Final Memory: 21M/201M
------------------------------------------------------------------------

appreciate for your work, thanks!

**Comment by AirtonB** [comment]
Exception:

org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]

**Comment by transytung** [comment]
You should re-check your hibernate config. Have you configured correct user/pwd or mapping all class that you new-created?
This is my config for example:
 `<property name="hibernate.dialect">org.hibernate.dialect.MySQLDialect</property>
        <property name="hibernate.connection.driver_class">com.mysql.jdbc.Driver</property>
        <property name="hibernate.connection.url">jdbc:mysql://localhost:3306/inventory?autoReconnect=true&amp;useUnicode=true&amp;createDatabaseIfNotExist=true&amp;characterEncoding=utf-8</property>
        <property name="hibernate.connection.CharSet">utf8</property>
        <property name="hibernate.connection.characterEncoding">utf8</property>
        <property name="hibernate.connection.username">sa</property>
        <property name="hibernate.connection.password">password</property>
 <property name="hibernate.current_session_context_class">thread</property>
        <mapping class="com.rafsan.inventory.entity.Category"/>
        <mapping class="com.rafsan.inventory.entity.Employee"/>
        <mapping class="com.rafsan.inventory.entity.Invoice"/>
        <mapping class="com.rafsan.inventory.entity.Product"/>
        <mapping class="com.rafsan.inventory.entity.Purchase"/>`

**Comment by AirtonB** [comment]
Still the same error, i did not change anything in the project.  :(

my full hibernate.cfg:

```
<hibernate-configuration>
    <session-factory>
        <property name="hibernate.dialect">org.hibernate.dialect.MySQLDialect</property> 
        <property name="hibernate.connection.driver_class">com.mysql.jdbc.Driver</property> 
        <property name="hibernate.connection.url">jdbc:mysql://localhost:3306/inventory?autoReconnect=true&amp;useUnicode=true&amp;createDatabaseIfNotExist=true&amp;characterEncoding=utf-8</property> 
        <property name="hibernate.connection.CharSet">utf8</property> 
        <property name="hibernate.connection.characterEncoding">utf8</property> 
        <property name="hibernate.connection.username">root</property> 
        <property name="hibernate.current_session_context_class">thread</property>
        <mapping class="com.rafsan.inventory.entity.Category"/>
        <mapping class="com.rafsan.inventory.entity.Employee"/>
        <mapping class="com.rafsan.inventory.entity.Invoice"/>
        <mapping class="com.rafsan.inventory.entity.Product"/>
        <mapping class="com.rafsan.inventory.entity.Purchase"/>
        <mapping class="com.rafsan.inventory.entity.Sale"/>
        <mapping class="com.rafsan.inventory.entity.Supplier"/>
    </session-factory>
</hibernate-configuration>
```




then:


**--- exec-maven-plugin:1.2.1:exec (default-cli) @ inventory ---**
_

1. jul 26, 2018 11:07:08 AM org.hibernate.Version logVersion
2. INFO: HHH000412: Hibernate Core {5.1.0.Final}
3. jul 26, 2018 11:07:08 AM org.hibernate.cfg.Environment <clinit>
### 4. INFO: HHH000206: hibernate.properties not found
5. jul 26, 2018 11:07:08 AM org.hibernate.cfg.Environment buildBytecodeProvider
6. INFO: HHH000021: Bytecode provider name : javassist
7. jul 26, 2018 11:07:08 AM org.hibernate.annotations.common.reflection.java.JavaReflectionManager <clinit>
8. INFO: HCANN000001: Hibernate Commons Annotations {5.0.1.Final}
9. jul 26, 2018 11:07:08 AM org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl configure
10. WARN: HHH10001002: Using Hibernate built-in connection pool (not for production use!)
11. jul 26, 2018 11:07:09 AM org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl buildCreator
12. INFO: HHH10001005: using driver [com.mysql.jdbc.Driver] at URL [jdbc:mysql://localhost:3306/inventory?autoReconnect=true&useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=utf-8]
13. jul 26, 2018 11:07:09 AM org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl buildCreator
14. INFO: HHH10001001: Connection properties: {user=root, CharSet=utf8, characterEncoding=utf8}
15. jul 26, 2018 11:07:09 AM org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl buildCreator
16. INFO: HHH10001003: Autocommit mode: false
17. jul 26, 2018 11:07:09 AM org.hibernate.engine.jdbc.connections.internal.PooledConnections <init>
18. INFO: HHH000115: Hibernate connection pool size: 20 (min=1)
### EXCEPTION => 19. ERRO: org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]
20. jul 26, 2018 11:07:19 AM org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl stop
21. INFO: HHH10001008: Cleaning up connection pool [jdbc:mysql://localhost:3306/inventory?autoReconnect=true&useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=utf-8]

_
------------------------------------------------------------------------
### UPDATE!
Works!!

Now the application starts fine but, when i press the login button nothing appears and show this error on console: 

**ERROR: Table 'inventory.employees' doesn't exist**
**Exception in thread "JavaFX Application Thread" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException**

**Comment by transytung** [comment]
Do the error occur when program run or while building? I used embedded Maven with eclipse for building so the log seem strange to me. You already setup MariaDB and run script to create scheme and tables right?
You can add my skype: transytung1135, i hope i can help you out of this.

**Comment by transytung** [comment]
follow the error message u should try to login db through 3rd DB administrator software such as HeidiSQL, log in and check your tables. Make sure you run the script inventory.sql to create tables and sample data, gud luck

**Comment by saravanaprakashb** [comment]
Hello Sir,

I am getting the Database connection error when running the application, please find the screenshot and hibernate config file below.

hibernate config file content:
<!DOCTYPE hibernate-configuration PUBLIC
"-//Hibernate/Hibernate Configuration DTD//EN"
"http://www.hibernate.org/dtd/hibernate-configuration.dtd">
<hibernate-configuration>
    <session-factory name="">
        <property name="hibernate.dialect">org.hibernate.dialect.MySQLDialect</property>
        <property name="hibernate.connection.driver_class">com.mysql.jdbc.Driver</property>
        <property name="hibernate.connection.url">jdbc:mysql://MahanPC:3306/inventory?autoReconnect=true&amp;useUnicode=true&amp;createDatabaseIfNotExist=true&amp;characterEncoding=utf-8&amp;useSSL=false</property>
        <property name="hibernate.connection.username">root</property>
        <property name="hibernate.connection.password">password</property>
        <property name="hibernate.current_session_context_class">thread</property>
        <mapping class="com.rafsan.inventory.entity.Category"/>
        <mapping class="com.rafsan.inventory.entity.Employee"/>
        <mapping class="com.rafsan.inventory.entity.Invoice"/>
        <mapping class="com.rafsan.inventory.entity.Product"/>
        <mapping class="com.rafsan.inventory.entity.Purchase"/>
        <mapping class="com.rafsan.inventory.entity.Sale"/>
        <mapping class="com.rafsan.inventory.entity.Supplier"/>
    </session-factory>
</hibernate-configuration>
![pos-database-error](https://user-images.githubusercontent.com/15572080/56467877-3fa66780-6442-11e9-90df-c78f2a567100.PNG)

**Comment by RizwanSohaib** [comment]
I have been trying to fix this error all the day. All that it required to work was changing mysql version in pom.xml

**I changed it from this;**
```
<dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>5.1.39</version>
</dependency>
```

**to this;**
```
<dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>5.1.48</version>
</dependency>
```
Hope this helps somebody.

**Comment by sebastian-prog** [comment]
Sometimes, the problem resides with the mysql installation. If you install the mysqlcommunity package (which usually installs mysql workbench too), then, there may be two problems.

Firstly, the server may not be running. This is usually because mscvp140.dll is missing, consequence of which the mysql server does not start. To fix this, simply download and install VC_redist for your machine. This should enable the server to start.

Secondly, if mysql was installed with a password, then this password need to be indicated in the inventory code. This can be done by supplying the password property in the hibernate.cfg.xml file. In the sample below, the mysql password was 'root'

<hibernate-configuration>
    <session-factory>
        ...
        <property name="hibernate.connection.username">root</property>
        <property name="hibernate.connection.password">root</property>
        ...
    </session-factory>
</hibernate-configuration>

**Comment by Muhammad-Qasim-Hayat** [comment]
On run I get this 


Oct 30, 2020 12:13:48 AM org.hibernate.Version logVersion
INFO: HHH000412: Hibernate Core {5.1.0.Final}
Oct 30, 2020 12:13:48 AM org.hibernate.cfg.Environment <clinit>
INFO: HHH000206: hibernate.properties not found
Oct 30, 2020 12:13:48 AM org.hibernate.cfg.Environment buildBytecodeProvider
INFO: HHH000021: Bytecode provider name : javassist
Oct 30, 2020 12:13:49 AM org.hibernate.annotations.common.reflection.java.JavaReflectionManager <clinit>
INFO: HCANN000001: Hibernate Commons Annotations {5.0.1.Final}
Oct 30, 2020 12:13:49 AM org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl configure
WARN: HHH10001002: Using Hibernate built-in connection pool (not for production use!)
Oct 30, 2020 12:13:49 AM org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl buildCreator
INFO: HHH10001005: using driver [com.mysql.jdbc.Driver] at URL [jdbc:mysql://localhost:3306/inventory]
Oct 30, 2020 12:13:49 AM org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl buildCreator
INFO: HHH10001001: Connection properties: {user=root}
Oct 30, 2020 12:13:49 AM org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl buildCreator
INFO: HHH10001003: Autocommit mode: false
Oct 30, 2020 12:13:49 AM org.hibernate.engine.jdbc.connections.internal.PooledConnections <init>
INFO: HHH000115: Hibernate connection pool size: 20 (min=1)
Fri Oct 30 00:13:49 PKT 2020 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
Oct 30, 2020 12:13:50 AM org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl stop
INFO: HHH10001008: Cleaning up connection pool [jdbc:mysql://localhost:3306/inventory]


Any idea how to run it ?

**Comment by sadatrafsanjani** [comment]
The appvis not able to connect to the database.

**Comment by NaheelSalman** [comment]
### First of all Thanks @sadatrafsanjani 
I changed my maven dependencies just by pasting this piece of code in pom.xml in netbeans 
`<repository>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
            <id>central</id>
            <name>Central Repository</name>
            <url>https://repo.maven.apache.org/maven2</url>
        </repository>
    </repositories>
<pluginRepositories>
    <pluginRepository>
        <releases>
            <updatePolicy>never</updatePolicy>
        </releases>
        <snapshots>
            <enabled>false</enabled>
        </snapshots>
        <id>central</id>
        <name>Central Repository</name>
        <url>https://repo.maven.apache.org/maven2</url>
    </pluginRepository>
</pluginRepositories>`
But still i got jbdc same error which is listed above now tell me
how to get connected with MYSQL local server since mysql server is running in the background but i haven't made any database of inventory.sql since i m expecting it would automatically generate database tables?
**Any Tutorial or help please** ! 
### I respect you give your attention and times to the questions

**Comment by Contente77** [comment]
Greetings Rafsanjani, I have downloaded the GIT, set it up in Netbeans and when I run it I get a polite DBConnection Error instructing me to contact the developer. Please direct me to the correct link/forum/document to resolve the DBConnection. Thanks a million

**Comment by sadatrafsanjani** [comment]
use my sql 5

**Comment by hamzafarooq951** [comment]
**I was getting same Database connection error when running project.**

I changed mysql-connector-java version in pom.

from this;

```
<dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>5.1.39</version>
</dependency>
```

to this;

```
<dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>YOUR_SQL_SERVER_VERSION</version>
</dependency>
````

Hope it helps.

**Comment by sadatrafsanjani** [comment]
seems good
